##  This code was written by Barry Guglielmo. Python 3.6.3 used on a windows 10 machine. Module used: Openpyxl.


##  OBJECTIVE_________________________________________________________________________________________
##  The purpose of this code is to compile the Report.TXT files that are generated by Agilent OpenLab
##  when integrating the chromatograms collected from our GC. It simply takes all integrated reports
##  and pastes them into an Excel Template. Believe it or not, this saves us a fair amount of tedium.



##  HOW TO RUN THIS CODE ______________________________________________________________________________
##  So long as you have python 3.6 or later downloaded you will only have to download one module called
##  openpyxl. To download openpyxl open a command prompt (cmd) this can be found by typing “cmd” in your
##  computers search bar In your command prompt type “pip install openpyxl”, if prompted that other modules
##  are necessary or other modules have not been found do the same “pip install” method for those modules.
##
##  Right Click File Run with IDLE 3.6.3 or Later. When this screen (the one you are reading now) shows up simply
##  press F5, or go to the Run -> Run Module on the top of the screen. When prompted by python shell type in file name.  
##  For example the file name  might be 032118S. Then the shell will prompt for the name you want to save the output excel sheet
##  as. I typically type the same name again 032118S.

## !!!! The only part of the code you need to change are the Paths to Fetch and Write data and the Sheet name to paste to !!!! ##
## !!!!                     Be sure to use forward slashes / for Path names                                               !!!! ## 
## !!!!                  You will see the Paths in the Top section of the Code                                            !!!! ##



#_________________________________________________________________#
#_________________________________________________________________#

##       Paths to Fetch Data and Write Data                      ##

        ###Fetch Data From the Run Here###
start_path = 'C:/Chem32/1/DATA/Jensen 2018/Phospholipid Fraction Experiments/Chromatograms/'

        ###Excel Files Live Here###
Excel_Path='C:/Chem32/1/DATA/Jensen 2018/Phospholipid Fraction Experiments/Excel/'

        ###Name of the Template To Paste Into###
Template_Name ='FA_Template_2018.xlsx'

        ###Sheet in Template to Paste To###
Sheet_Name = 'Sheet1'

#_________________________________________________________________#
#_________________________________________________________________#

#Dependancies
import os
from openpyxl import load_workbook

#Get Input form user
file = input('Enter Chromatogram File Name: ')
save = input('Enter Name to Save Excel: ')


chroms_path = os.chdir( start_path + file)
#This assumes only 1 subfile. Multiple subfiles are possible SO be warry
next_folder = str(os.listdir(chroms_path))
#This is where the Samples Live
sample_path = str(start_path) + str(file) + '/' + str(next_folder[2:(len(next_folder)-2)])
os.chdir(sample_path)
#_________________________________________________________________#
#_________________________________________________________________#
#make a list of the chrom files
list_chrom_files = os.listdir(sample_path)
#get rid of the files we dont need
my_samp_list = []
for i in list_chrom_files:
    for j in i:
        if j =='D':
            my_samp_list.append(i)
#remove Mehtods and Standby (they are in cuz of the letter D)
del my_samp_list[-1]
del my_samp_list[-1]
#_________________________________________________________________#
#_________________________________________________________________#

#integrated ids
integrated_ids = []
#sample ids
sid = []
#array of data from each samples and the totals
all_dat = []
tot_dat = []
#_________________________________________________________________#
#_________________________________________________________________#
#This is my most significant loop.
#go into each sample file from the list created
for sample in my_samp_list:
    #Change path to the next folder
    os.chdir(str(sample_path)+'/'+str(sample))
    #Integrated default true
    integrated = True
    #subfiles to determine if integrated
    sub_files = os.listdir(str(sample_path)+'/'+str(sample))
    count = 0
    for f in sub_files:
        count += 1
    if count < 15:
        integrated = False
#_________________________________________________________________#
#_________________________________________________________________#
    #If it was integrated get my data : The following step export to excel
    if integrated ==True:
        print(sample)
        start = 0
        end = False
        first_total = True
        #set first run through = to true
        first_one =True
        #Data Array
        data = []
        #totals array
        totals = []
        #open report
        open_file = open('Report.TXT', 'r')
        #Itterate through file
        for i, line in enumerate(open_file):
            #Get the Name
            if i == 2:
                name = line[27:]
                #clean up pesky names
                name = str(name.replace('\x00',''))
                name = str(name.replace('\n', ''))
                #add name to integrated id list
                integrated_ids.append(name)
                sid.append(sample)

            elif 'Totals :' in line.replace('\x00','') and first_total == True:
                end = True
                first_total = False
                clean_d = line.replace('\x00','')
                #this may be an issue but keep moving
                totals.append(clean_d[25:37])
                totals.append(clean_d[40:47])
            #if time is appropriate get that data
            elif start > 0 and end == False:
                clean_d = line.replace('\x00','')
                data.append(clean_d[40:47])
                
            #otherwise wait to see this
            else:
                x = line.replace('\x00','')
                if "----|-------|------|-------|----------|--------|---------------------" in x and first_one == True:
                    start = i
                    first_one = False
                    
        #There are blanks in the data so This gets them out
        for y in data:
            if y =='':
                data.remove(y)
        all_dat.append(data)                   
        tot_dat.append(totals)
#_________________________________________________________________#
#_________________________________________________________________#
#Export the Data to Excel with Openpyxl
os.chdir(Excel_Path)
wb = load_workbook(Template_Name)
ws = wb.active
A = 2
for i in range(0,len(sid)):   
    B = 4
    C=0
    
    for j in all_dat[i]:
        wb[Sheet_Name].cell(row = A , column = B).value = all_dat[i][B-4]
        B+=1
    B+=1
    for k in tot_dat[i]:
        wb[Sheet_Name].cell(row = A , column = B).value = tot_dat[i][C]
        B+=1
        C+=1
    A+=1

wb.save(str(save)+".xlsx")

for item in integrated_ids:
    print(item)














    
